# Funding options for GitHub Copilot Agent Extension
# خيارات التمويل لإضافة GitHub Copilot Agent

# GitHub Sponsors
github: [SalehKadah]

# Other platforms (uncomment and add your usernames)
# patreon: username
# open_collective: project
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ['https://www.kadahtech.com/donate', 'https://paypal.me/kadahtech']
