name: copilot_extension
description: >
  إضافة وكيل الذكاء الاصطناعي GitHub Copilot لبيئة التطوير SA IDE - نظام متقدم لإكمال الكود المدعوم بالذكاء الاصطناعي مع دعم 9+ لغات برمجة، تحليلات متقدمة، تخزين مؤقت عالي الأداء، وواجهة مستخدم حديثة.
  GitHub Copilot AI Agent Extension for SA IDE - Advanced AI-powered code completion system with 9+ programming languages support, advanced analytics, high-performance caching, and modern UI.
version: 1.0.0
author: Saleh Kadah / Kadah Tech
homepage: https://www.kadahtech.com/copilot-extension
repository: https://github.com/kadahtech/copilot-extension
issue_tracker: https://github.com/kadahtech/copilot-extension/issues
documentation: https://github.com/kadahtech/copilot-extension/wiki

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # التواصل مع الشبكة - Network communication
  http: ^1.1.0
  dio: ^5.3.3
  
  # إدارة الحالة - State management
  provider: ^6.0.5
  riverpod: ^2.4.0
  
  # تخزين البيانات المحلية - Local data storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # معالجة JSON - JSON processing
  json_annotation: ^4.8.1
  
  # معالجة النصوص - Text processing
  intl: ^0.18.1
  
  # تسجيل الأحداث - Logging
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # أدوات البناء - Build tools
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  
  # التحليل والاختبار - Analysis and testing
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  test: ^1.24.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/icons/
